# Generated by Django 5.0.6 on 2026-08-11 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=120)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('last_visited_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_count', '-last_visited_at'],
                'indexes': [models.Index(fields=['user', '-last_visited_at'], name='screenvisit_user_recent_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='screenvisit',
            constraint=models.UniqueConstraint(fields=('user', 'url_name'), name='unique_user_screen_visit'),
        ),
    ]
