# Generated by Django 5.0.6 on 2026-08-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenvisit',
            name='favorited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screenvisit',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
