# Generated by Django 5.0.6 on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="id_sm",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]

