# Generated by Django 5.0.6 on 2026-08-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_id_erp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_internal',
            field=models.BooleanField(default=True),
        ),
    ]
