# Generated by Django 5.0.6 on 2026-08-19 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_representative_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dashes_ai_daily_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DashesAiUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField(db_index=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('last_request_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashes_ai_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usage_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='dashesaiusage',
            constraint=models.UniqueConstraint(fields=('user', 'usage_date'), name='unique_dashes_ai_usage_per_day'),
        ),
    ]
