# Generated by Django 5.0.6 on 2026-09-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_dashes_ai_daily_limit_dashesaiusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_support_attendant',
            field=models.BooleanField(default=False),
        ),
    ]
