# Generated by Django 6.0.2 on 2026-02-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userQueue',
            fields=[
                ('user_code', models.CharField(max_length=10)),
                ('n_register', models.IntegerField(primary_key=True, serialize=False)),
                ('a_ticket', models.CharField(max_length=30)),
                ('f_conclusion_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('n_status_code', models.IntegerField()),
                ('a_description', models.CharField(max_length=250)),
                ('n_type_group', models.IntegerField()),
                ('n_type_code', models.IntegerField()),
                ('d_predicted_date_start', models.DateField()),
                ('d_predicted_date_end', models.DateField()),
                ('t_predicted_time_start', models.TimeField()),
                ('t_predicted_time_end', models.TimeField()),
                ('d_real_date_start', models.DateField()),
                ('d_real_date_end', models.DateField()),
                ('d_real_time_start', models.TimeField()),
                ('t_real_time_end', models.TimeField()),
                ('n_queue_position', models.IntegerField()),
            ],
        ),
    ]
