# Generated by Django 6.0.2 on 2026-02-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqueue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userqueue',
            name='a_description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='userqueue',
            name='a_ticket',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='userqueue',
            name='d_predicted_date_end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='userqueue',
            name='d_predicted_date_start',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='userqueue',
            name='d_real_date_end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='userqueue',
            name='d_real_date_start',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='userqueue',
            name='d_real_time_start',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='userqueue',
            name='f_conclusion_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userqueue',
            name='n_status_code',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userqueue',
            name='n_type_code',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userqueue',
            name='n_type_group',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userqueue',
            name='t_predicted_time_end',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='userqueue',
            name='t_predicted_time_start',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='userqueue',
            name='t_real_time_end',
            field=models.TimeField(blank=True),
        ),
    ]
