# Generated by Django 6.0.2 on 2026-02-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqueue', '0003_alter_userqueue_a_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userqueue',
            name='n_register',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
