# Generated by Django 6.0.2 on 2026-02-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqueue', '0004_alter_userqueue_n_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userqueue',
            name='n_queue_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
