# Generated by Django 6.0.2 on 2026-02-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqueue', '0005_alter_userqueue_n_queue_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='concludedTasks',
            fields=[
                ('user_code', models.CharField(max_length=10)),
                ('n_register', models.AutoField(primary_key=True, serialize=False)),
                ('a_ticket', models.CharField(blank=True, max_length=30, null=True)),
                ('f_conclusion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('n_status_code', models.IntegerField(blank=True, null=True)),
                ('a_description', models.CharField(blank=True, max_length=250, null=True)),
                ('n_type_group', models.IntegerField(blank=True, null=True)),
                ('n_type_code', models.IntegerField(blank=True, null=True)),
                ('d_predicted_date_start', models.DateField(blank=True, null=True)),
                ('d_predicted_date_end', models.DateField(blank=True, null=True)),
                ('t_predicted_time_start', models.TimeField(blank=True, null=True)),
                ('t_predicted_time_end', models.TimeField(blank=True, null=True)),
                ('d_real_date_start', models.DateField(blank=True, null=True)),
                ('d_real_date_end', models.DateField(blank=True, null=True)),
                ('d_real_time_start', models.TimeField(blank=True, null=True)),
                ('t_real_time_end', models.TimeField(blank=True, null=True)),
                ('n_queue_position', models.IntegerField(blank=True, null=True)),
                ('d_conclusion_date', models.DateField(auto_now=True)),
                ('d_conclusion_time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
