# Generated by Codex on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiqueue", "0006_concludedtasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="userqueue",
            name="f_total_predicted_time",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="userqueue",
            name="f_total_real_time",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="userqueue",
            name="f_predicted_real_diference",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="concludedtasks",
            name="f_total_predicted_time",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="concludedtasks",
            name="f_total_real_time",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="concludedtasks",
            name="f_predicted_real_diference",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]

