# Generated by Codex on 2026-03-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tiqueue", "0007_add_time_metrics_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TaskType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80)),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="types", to="tiqueue.taskgroup")),
            ],
            options={
                "unique_together": {("group", "name")},
            },
        ),
        migrations.AddField(
            model_name="userqueue",
            name="task_group",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="tiqueue.taskgroup"),
        ),
        migrations.AddField(
            model_name="userqueue",
            name="task_type",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="tiqueue.tasktype"),
        ),
        migrations.AddField(
            model_name="concludedtasks",
            name="task_group",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="tiqueue.taskgroup"),
        ),
        migrations.AddField(
            model_name="concludedtasks",
            name="task_type",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="tiqueue.tasktype"),
        ),
    ]

