# Generated by Django 5.0.6 on 2026-03-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqueue', '0008_task_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskgroup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
