# Generated by Codex on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiqueue", "0008_task_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktype",
            name="color",
            field=models.CharField(default="#5CD6A3", max_length=7),
        ),
    ]

