# Generated by Codex on 2026-03-17

from django.db import migrations, models


def mark_position_one_as_current(apps, schema_editor):
    UserQueue = apps.get_model("tiqueue", "userQueue")
    UserQueue.objects.filter(n_queue_position=1).update(is_current=True)


class Migration(migrations.Migration):

    dependencies = [
        ("tiqueue", "0009_task_type_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="userqueue",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_position_one_as_current, migrations.RunPython.noop),
    ]

