# Generated by Django 5.0.6 on 2026-03-17 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiqueue', '0009_alter_taskgroup_id_alter_tasktype_id'),
        ('tiqueue', '0009_task_type_color'),
    ]

    operations = [
    ]
