# Generated by Codex on 2026-03-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tiqueue", "0010_add_is_current"),
        ("tiqueue", "0010_merge_20260317_0827"),
    ]

    operations = []
