# Generated by Codex on 2026-03-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tiqueue", "0011_merge_20260317_1130"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistChoiceGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChecklistTemplate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChecklistSection",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "template",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="tiqueue.checklisttemplate"),
                ),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="ChecklistChoiceOption",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=120)),
                (
                    "group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="options", to="tiqueue.checklistchoicegroup"),
                ),
            ],
            options={"unique_together": {("group", "label")}},
        ),
        migrations.CreateModel(
            name="ChecklistField",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=200)),
                ("help_text", models.CharField(blank=True, max_length=240, null=True)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto curto"),
                            ("textarea", "Texto longo"),
                            ("number", "Numero"),
                            ("date", "Data"),
                            ("time", "Hora"),
                            ("boolean", "Sim/Nao"),
                            ("single_choice", "Escolha unica"),
                            ("multi_choice", "Multipla escolha"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "choice_group",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fields", to="tiqueue.checklistchoicegroup"),
                ),
                (
                    "section",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fields", to="tiqueue.checklistsection"),
                ),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="ChecklistEntry",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=160, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "template",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="entries", to="tiqueue.checklisttemplate"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChecklistAnswer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value_text", models.TextField(blank=True, null=True)),
                ("value_number", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("value_date", models.DateField(blank=True, null=True)),
                ("value_time", models.TimeField(blank=True, null=True)),
                ("value_bool", models.BooleanField(blank=True, null=True)),
                (
                    "entry",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="tiqueue.checklistentry"),
                ),
                (
                    "field",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="tiqueue.checklistfield"),
                ),
                (
                    "selected_options",
                    models.ManyToManyField(blank=True, to="tiqueue.checklistchoiceoption"),
                ),
            ],
            options={"unique_together": {("entry", "field")}},
        ),
    ]
