# Generated by Codex on 2026-04-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tiqueue", "0012_checklists"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueTaskDetail",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=240)),
                ("is_done", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "queue_item",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="details", to="tiqueue.userqueue"),
                ),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),
    ]

