# Generated by Codex on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiqueue", "0013_queue_task_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="queuetaskdetail",
            name="duration_hours",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]

