# Generated by Codex on 2026-04-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tiqueue", "0015_projects_roadmap"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectKanbanColumn",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80)),
                ("color", models.CharField(default="#343955", max_length=7)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="kanban_columns", to="tiqueue.project"),
                ),
            ],
            options={"ordering": ["sort_order", "id"], "unique_together": {("project", "name")}},
        ),
        migrations.CreateModel(
            name="ProjectKanbanCard",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "priority",
                    models.IntegerField(choices=[(1, "Baixa"), (2, "Media"), (3, "Alta")], default=2),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "column",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cards", to="tiqueue.projectkanbancolumn"),
                ),
                (
                    "project",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="kanban_cards", to="tiqueue.project"),
                ),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),
    ]

