# Generated by Codex on 2026-04-20

from django.db import migrations, models
import django.db.models.deletion


DEFAULT_COLUMNS = [
    ("Backlog", "#343955", 1),
    ("Em andamento", "#3a3f61", 2),
    ("Bloqueado", "#5a3a3a", 3),
    ("Concluido", "#1f5a3a", 4),
]


def _normalize(value):
    return (value or "").strip().lower()


def _ensure_columns(ProjectKanbanColumn, project):
    columns = list(ProjectKanbanColumn.objects.filter(project=project).order_by("sort_order", "id"))
    if columns:
        return columns

    for name, color, order in DEFAULT_COLUMNS:
        ProjectKanbanColumn.objects.create(project=project, name=name, color=color, sort_order=order)
    return list(ProjectKanbanColumn.objects.filter(project=project).order_by("sort_order", "id"))


def _pick_column(columns, status):
    status = _normalize(status) or "planned"

    def find(tokens):
        for col in columns:
            name = _normalize(col.name)
            if any(t in name for t in tokens):
                return col
        return None

    if status == "done":
        return find(["conclu", "done"]) or columns[-1]
    if status == "blocked":
        return find(["bloq", "block"]) or (columns[2] if len(columns) >= 3 else columns[0])
    if status == "doing":
        return find(["andamento", "doing", "exec"]) or (columns[1] if len(columns) >= 2 else columns[0])
    return find(["backlog", "planej", "todo", "to do"]) or columns[0]


def forward_link_roadmap_cards(apps, schema_editor):
    Project = apps.get_model("tiqueue", "Project")
    ProjectRoadmapItem = apps.get_model("tiqueue", "ProjectRoadmapItem")
    ProjectKanbanColumn = apps.get_model("tiqueue", "ProjectKanbanColumn")
    ProjectKanbanCard = apps.get_model("tiqueue", "ProjectKanbanCard")

    for project in Project.objects.all().iterator():
        columns = _ensure_columns(ProjectKanbanColumn, project)
        roadmap_items = ProjectRoadmapItem.objects.filter(project=project).order_by("sort_order", "id")

        for item in roadmap_items.iterator():
            # Try to reuse an existing card with same title before creating a new one.
            existing = (
                ProjectKanbanCard.objects.filter(
                    project=project,
                    roadmap_item__isnull=True,
                    title=item.title,
                )
                .order_by("id")
                .first()
            )
            if existing:
                existing.roadmap_item = item
                existing.description = existing.description or item.description
                existing.due_date = existing.due_date or item.end_date
                existing.save(update_fields=["roadmap_item", "description", "due_date", "updated_at"])
                continue

            column = _pick_column(columns, item.status)
            max_sort = (
                ProjectKanbanCard.objects.filter(project=project, column=column)
                .aggregate(models.Max("sort_order"))
                .get("sort_order__max")
            )
            next_sort = int(max_sort or 0) + 1

            ProjectKanbanCard.objects.create(
                project=project,
                column=column,
                roadmap_item=item,
                title=item.title,
                description=item.description or None,
                due_date=item.end_date,
                sort_order=next_sort,
            )


def backward_unlink_roadmap_cards(apps, schema_editor):
    ProjectKanbanCard = apps.get_model("tiqueue", "ProjectKanbanCard")
    ProjectKanbanCard.objects.filter(roadmap_item__isnull=False).update(roadmap_item=None)


class Migration(migrations.Migration):

    dependencies = [
        ("tiqueue", "0016_project_kanban"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectkanbancard",
            name="roadmap_item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kanban_card",
                to="tiqueue.projectroadmapitem",
            ),
        ),
        migrations.RunPython(forward_link_roadmap_cards, backward_unlink_roadmap_cards),
    ]
