# Generated by Codex on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiqueue", "0017_link_roadmap_kanban"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeniorSystemUpdate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("erp_version", models.CharField(max_length=40)),
                ("hcm_version", models.CharField(max_length=40)),
                ("sde_version", models.CharField(max_length=40)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("download_date", models.DateField(blank=True, null=True)),
                ("planned_apply_date", models.DateField(blank=True, null=True)),
                ("real_apply_date", models.DateField(blank=True, null=True)),
                ("in_production", models.BooleanField(default=False)),
                ("in_test_base", models.BooleanField(default=False)),
                ("in_simulation_base", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-release_date", "-created_at", "-id"]},
        ),
    ]
