# Generated by Codex on 2026-04-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tiqueue", "0018_senior_system_updates"),
    ]

    operations = [
        migrations.CreateModel(
            name="WifiVoucherGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=80, null=True)),
                ("duration_hours", models.PositiveIntegerField()),
                ("expected_quantity", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["duration_hours", "id"]},
        ),
        migrations.CreateModel(
            name="WifiVoucher",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("voucher_code", models.CharField(max_length=40, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "Disponivel"), ("pending", "Pendente"), ("used", "Usado")],
                        default="available",
                        max_length=12,
                    ),
                ),
                ("inserted_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouchers",
                        to="tiqueue.wifivouchergroup",
                    ),
                ),
            ],
            options={"ordering": ["group__duration_hours", "status", "voucher_code", "id"]},
        ),
    ]
