# Generated by Codex on 2026-04-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tiqueue", "0019_wifi_vouchers"),
    ]

    operations = [
        migrations.CreateModel(
            name="HubToolCategory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["sort_order", "name", "id"]},
        ),
        migrations.CreateModel(
            name="HubTool",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("link", models.URLField(max_length=500)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to="tiqueue.hubtoolcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name", "id"],
                "unique_together": {("category", "name")},
            },
        ),
    ]
