# Generated by Codex on 2026-04-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_id"),
        ("tiqueue", "0020_hub_tools"),
    ]

    operations = [
        migrations.CreateModel(
            name="HubUserTool",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category_name", models.CharField(default="Meu HUB", max_length=80)),
                ("name", models.CharField(max_length=120)),
                ("link", models.URLField(max_length=500)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_tools",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "ordering": ["category_name", "sort_order", "name", "id"],
                "unique_together": {("user", "category_name", "name")},
            },
        ),
    ]
