# Generated by Codex on 2026-04-27

from django.db import migrations, models
import django.db.models.deletion


def forward_fill_categories(apps, schema_editor):
    HubUserTool = apps.get_model("tiqueue", "HubUserTool")
    HubUserToolCategory = apps.get_model("tiqueue", "HubUserToolCategory")

    pairs = {}
    for tool in HubUserTool.objects.all().iterator():
        cat_name = (tool.category_name or "Meu HUB").strip() or "Meu HUB"
        key = (tool.user_id, cat_name)
        cat = pairs.get(key)
        if cat is None:
            cat, _ = HubUserToolCategory.objects.get_or_create(
                user_id=tool.user_id,
                name=cat_name,
                defaults={"sort_order": 0, "is_active": True},
            )
            pairs[key] = cat
        tool.category_id = cat.id
        tool.save(update_fields=["category"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_id"),
        ("tiqueue", "0021_hub_user_tools"),
    ]

    operations = [
        migrations.CreateModel(
            name="HubUserToolCategory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_tool_categories",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name", "id"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.AddField(
            model_name="hubusertool",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tools",
                to="tiqueue.hubusertoolcategory",
            ),
        ),
        migrations.RunPython(forward_fill_categories, migrations.RunPython.noop),
    ]
