# Generated by Django 5.0.6 on 2026-06-16 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqueue', '0044_userqueuesavedview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userqueuecustomcolumn',
            name='color',
            field=models.CharField(default='#61688c', max_length=7),
        ),
        migrations.AddField(
            model_name='userqueuecustomcolumn',
            name='field_type',
            field=models.CharField(choices=[('text', 'Texto'), ('select', 'Lista'), ('number', 'Numero'), ('date', 'Data'), ('checkbox', 'Checkbox')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='concludedtasks',
            name='estimated_effort_level',
            field=models.CharField(default='medium', max_length=40),
        ),
        migrations.AlterField(
            model_name='concludedtasks',
            name='priority_level',
            field=models.CharField(default='medium', max_length=40),
        ),
        migrations.AlterField(
            model_name='userqueue',
            name='estimated_effort_level',
            field=models.CharField(default='medium', max_length=40),
        ),
        migrations.AlterField(
            model_name='userqueue',
            name='priority_level',
            field=models.CharField(default='medium', max_length=40),
        ),
        migrations.CreateModel(
            name='UserQueueCustomColumnOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=80)),
                ('color', models.CharField(default='#61688c', max_length=7)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tiqueue.userqueuecustomcolumn')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('column', 'value')},
            },
        ),
        migrations.CreateModel(
            name='UserQueueFieldOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(choices=[('priority_level', 'Prioridade'), ('estimated_effort_level', 'Nivel estimado')], max_length=40)),
                ('value', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=60)),
                ('color', models.CharField(default='#61688c', max_length=7)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_field_options', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('user', 'field_key', 'value')},
            },
        ),
    ]
