# Generated by Django 5.0.6 on 2026-06-26 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqueue', '0046_queue_task_extra_collaborators'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRoadmapSubtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=240)),
                ('is_done', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roadmap_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tiqueue.projectroadmapitem')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
