# Generated by Django 5.0.6 on 2026-07-08 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqueue', '0050_alter_contractrecord_id_alter_datamodelfield_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority_level', models.CharField(default='medium', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('assumed', 'Em atendimento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='pending', max_length=16)),
                ('assumed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_portal_demands', to=settings.AUTH_USER_MODEL)),
                ('linked_queue_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_sources', to='tiqueue.userqueue')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_demands', to=settings.AUTH_USER_MODEL)),
                ('task_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiqueue.taskgroup')),
                ('task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiqueue.tasktype')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
