# Generated by Django 5.0.6 on 2026-07-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqueue', '0052_portaldemandmessage_portaldemandattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaldemand',
            name='feedback_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portaldemand',
            name='feedback_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Muito insatisfeito'), (2, 'Insatisfeito'), (3, 'Neutro'), (4, 'Satisfeito'), (5, 'Muito satisfeito')], null=True),
        ),
        migrations.AddField(
            model_name='portaldemand',
            name='feedback_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
