# Generated by Django 5.0.6 on 2026-07-14 14:08

import random
import string
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_portal_demand_access_codes(apps, schema_editor):
    PortalDemand = apps.get_model('tiqueue', 'PortalDemand')

    for demand in PortalDemand.objects.filter(access_code__isnull=True).iterator():
        while True:
            candidate = f"{random.randint(0, 999):03d}-" + "".join(
                random.choice(string.ascii_uppercase) for _ in range(5)
            )
            if not PortalDemand.objects.filter(access_code=candidate).exists():
                PortalDemand.objects.filter(pk=demand.pk).update(access_code=candidate)
                break


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('tiqueue', '0053_portaldemand_feedback_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portaldemand',
            name='access_code',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True, unique=True),
        ),
        migrations.RunPython(populate_portal_demand_access_codes, noop_reverse),
        migrations.CreateModel(
            name='PortalDemandCustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, unique=True)),
                ('field_key', models.SlugField(blank=True, max_length=80, unique=True)),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('textarea', 'Texto longo'), ('select', 'Lista'), ('number', 'Numero'), ('date', 'Data'), ('checkbox', 'Checkbox')], default='text', max_length=20)),
                ('placeholder', models.CharField(blank=True, max_length=160, null=True)),
                ('help_text', models.CharField(blank=True, max_length=240, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_demand_custom_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortalDemandCustomFieldOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=80)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tiqueue.portaldemandcustomfield')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('field', 'value')},
            },
        ),
        migrations.CreateModel(
            name='PortalDemandCustomValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='tiqueue.portaldemand')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='tiqueue.portaldemandcustomfield')),
            ],
            options={
                'ordering': ['field__sort_order', 'field__id', 'id'],
                'unique_together': {('demand', 'field')},
            },
        ),
    ]
