# Generated by Django 5.0.6 on 2026-07-15 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqueue', '0055_portaldemandmessage_work_ended_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portaldemand',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portaldemand',
            name='first_response_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portaldemand',
            name='resolution_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portaldemandcustomfield',
            name='task_groups',
            field=models.ManyToManyField(blank=True, related_name='portal_custom_fields', to='tiqueue.taskgroup'),
        ),
        migrations.AddField(
            model_name='portaldemandcustomfield',
            name='task_types',
            field=models.ManyToManyField(blank=True, related_name='portal_custom_fields', to='tiqueue.tasktype'),
        ),
        migrations.AddField(
            model_name='portaldemandmessage',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PortalCannedResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('suggest_internal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_canned_responses', to=settings.AUTH_USER_MODEL)),
                ('task_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_canned_responses', to='tiqueue.taskgroup')),
                ('task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_canned_responses', to='tiqueue.tasktype')),
            ],
            options={
                'ordering': ['sort_order', 'title', 'id'],
            },
        ),
        migrations.AddField(
            model_name='portaldemandmessage',
            name='canned_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='tiqueue.portalcannedresponse'),
        ),
        migrations.CreateModel(
            name='PortalDemandSlaPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=240, null=True)),
                ('priority_level', models.CharField(blank=True, max_length=40, null=True)),
                ('first_response_minutes', models.PositiveIntegerField(default=60)),
                ('resolution_minutes', models.PositiveIntegerField(default=480)),
                ('auto_assign_on_create', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_attendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_default_sla_policies', to=settings.AUTH_USER_MODEL)),
                ('task_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_sla_policies', to='tiqueue.taskgroup')),
                ('task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_sla_policies', to='tiqueue.tasktype')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='portaldemand',
            name='sla_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demands', to='tiqueue.portaldemandslapolicy'),
        ),
    ]
