# Generated by Django 5.0.6 on 2026-07-31 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqueue', '0059_projectmilestone_anchor_item_and_milestone_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_minutes', models.PositiveIntegerField(default=25)),
                ('break_minutes', models.PositiveIntegerField(default=5)),
                ('accomplishment', models.CharField(blank=True, default='', max_length=240)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at', '-id'],
            },
        ),
    ]
