# Generated by Django 5.0.6 on 2026-08-11 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqueue', '0062_openai_customer_insights'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('url_name', models.CharField(help_text='Nome da rota Django que abre o painel (ex.: dashesCustomerDnaPage).', max_length=120)),
                ('icon_path', models.TextField(blank=True, help_text='Conteúdo do <svg> exibido na sidebar do Dashes.', null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DashboardAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='tiqueue.dashboard')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_dashboard_accesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dashboard__display_order', 'dashboard__name', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='dashboardaccess',
            constraint=models.UniqueConstraint(fields=('user', 'dashboard'), name='unique_user_dashboard_access'),
        ),
    ]
