# Generated by Django 5.0.6 on 2026-08-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqueue', '0064_seed_customer_dna_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinsightsnapshot',
            name='member_customer_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerinsightsnapshot',
            name='view_mode',
            field=models.CharField(choices=[('individual', 'Cliente individual'), ('group', 'Grupo econômico')], default='individual', max_length=12),
        ),
    ]
