# Generated by Django 5.0.6 on 2026-08-20 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqueue', '0066_dashboard_ti_bi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItBiInsightSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(max_length=8)),
                ('company_key', models.CharField(max_length=8)),
                ('scope_label', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('prepared', 'Preparado'), ('processing', 'Processando na IA'), ('completed', 'Concluído'), ('error', 'Erro')], default='prepared', max_length=20)),
                ('source_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('metrics', models.JSONField(default=dict)),
                ('ai_payload', models.JSONField(default=dict)),
                ('ai_response', models.JSONField(blank=True, default=dict)),
                ('ai_model', models.CharField(blank=True, max_length=80, null=True)),
                ('ai_response_id', models.CharField(blank=True, max_length=120, null=True)),
                ('ai_input_tokens', models.PositiveIntegerField(default=0)),
                ('ai_output_tokens', models.PositiveIntegerField(default=0)),
                ('ai_total_tokens', models.PositiveIntegerField(default=0)),
                ('ai_error', models.TextField(blank=True, null=True)),
                ('ai_requested_at', models.DateTimeField(blank=True, null=True)),
                ('ai_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_bi_insight_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='itbiinsightsnapshot',
            constraint=models.UniqueConstraint(fields=('period_key', 'company_key'), name='unique_it_bi_insight_scope'),
        ),
    ]
