# Generated by Django 5.0.6 on 2026-08-20 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqueue', '0067_itbiinsightsnapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itbiinsightsnapshot',
            name='unique_it_bi_insight_scope',
        ),
        migrations.AddField(
            model_name='itbiinsightsnapshot',
            name='attendant_key',
            field=models.CharField(default='all', max_length=120),
        ),
        migrations.AddConstraint(
            model_name='itbiinsightsnapshot',
            constraint=models.UniqueConstraint(fields=('period_key', 'company_key', 'attendant_key'), name='unique_it_bi_insight_scope'),
        ),
    ]
