# Generated by Django 5.0.6 on 2026-08-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqueue', '0069_travel_bi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itbiinsightsnapshot',
            name='period_key',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='travelbiinsightsnapshot',
            name='period_key',
            field=models.CharField(max_length=20),
        ),
    ]
