# Generated by Django 5.0.6 on 2026-09-02 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqueue', '0070_widen_bi_period_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaldemand',
            name='reopen_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portaldemand',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portaldemand',
            name='requester_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demands', to='tiqueue.portalrequestersector'),
        ),
        migrations.AddField(
            model_name='portaldemand',
            name='sla_paused_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portaldemand',
            name='waiting_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portaldemand',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('assumed', 'Em atendimento'), ('waiting_requester', 'Aguardando solicitante'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='portaldemandlog',
            name='event_type',
            field=models.CharField(choices=[('assumed', 'Assunção'), ('transferred', 'Transferência'), ('worklog', 'Apontamento'), ('waiting', 'Aguardando solicitante'), ('resumed', 'Retomada'), ('completed', 'Conclusão'), ('reopened', 'Reabertura'), ('cancelled', 'Cancelamento'), ('ai_routed', 'Roteamento IA')], max_length=20),
        ),
    ]
