# Generated by Django 5.0.6 on 2026-09-10 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


DASHBOARD = {
    "slug": "romaneios",
    "name": "BI de Romaneios",
    "description": "Produtividade da contagem de pallets por matrícula",
    "url_name": "dashesRomaneioBiPage",
    "display_order": 40,
    "is_active": True,
    "icon_path": (
        '<rect x="4" y="10" width="16" height="9" rx="1.2"/>'
        '<path d="M4 14h16M8 10V7a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v3"/>'
    ),
}


def create_dashboard(apps, schema_editor):
    """Registra o painel no catálogo — é ele que monta a sidebar e as permissões."""
    Dashboard = apps.get_model("tiqueue", "Dashboard")
    Dashboard.objects.update_or_create(slug=DASHBOARD["slug"], defaults=DASHBOARD)


def remove_dashboard(apps, schema_editor):
    Dashboard = apps.get_model("tiqueue", "Dashboard")
    Dashboard.objects.filter(slug=DASHBOARD["slug"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tiqueue', '0071_portaldemand_reopen_count_portaldemand_reopened_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RomaneioBiInsightSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(max_length=20)),
                ('branch_key', models.CharField(default='all', max_length=20)),
                ('stage_key', models.CharField(default='all', max_length=8)),
                ('matricula_key', models.CharField(default='all', max_length=20)),
                ('scope_label', models.CharField(blank=True, max_length=160, null=True)),
                ('status', models.CharField(choices=[('prepared', 'Preparado'), ('processing', 'Processando na IA'), ('completed', 'Concluído'), ('error', 'Erro')], default='prepared', max_length=20)),
                ('source_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('metrics', models.JSONField(default=dict)),
                ('ai_payload', models.JSONField(default=dict)),
                ('ai_response', models.JSONField(blank=True, default=dict)),
                ('ai_model', models.CharField(blank=True, max_length=80, null=True)),
                ('ai_response_id', models.CharField(blank=True, max_length=120, null=True)),
                ('ai_input_tokens', models.PositiveIntegerField(default=0)),
                ('ai_output_tokens', models.PositiveIntegerField(default=0)),
                ('ai_total_tokens', models.PositiveIntegerField(default=0)),
                ('ai_error', models.TextField(blank=True, null=True)),
                ('ai_requested_at', models.DateTimeField(blank=True, null=True)),
                ('ai_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='romaneio_bi_insight_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='romaneiobiinsightsnapshot',
            constraint=models.UniqueConstraint(fields=('period_key', 'branch_key', 'stage_key', 'matricula_key'), name='unique_romaneio_bi_insight_scope'),
        ),
        migrations.RunPython(create_dashboard, remove_dashboard),
    ]
