# Generated by Codex on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hqbooking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="headquartersreservation",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="headquartersreservation",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="headquartersreservation",
            name="reason",
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
