# Generated by Codex on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hqbooking", "0002_reservation_time_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="headquartersreservation",
            name="reserved_date",
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name="headquartersreservation",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pendente"), ("APPROVED", "Aprovada"), ("REJECTED", "Recusada")],
                db_index=True,
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="headquartersreservation",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model("hqbooking", "HeadquartersReservation").objects.all().update(status="APPROVED"),
            migrations.RunPython.noop,
        ),
    ]
