# Generated by Codex on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hqbooking", "0003_approval_flow"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeadquartersEnvironment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True)),
                ("description", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name", "id"]},
        ),
        migrations.CreateModel(
            name="HeadquartersDateBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("blocked_date", models.DateField(unique=True)),
                ("reason", models.CharField(blank=True, max_length=200, null=True)),
                ("blocked_by", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["blocked_date", "id"]},
        ),
        migrations.AddField(
            model_name="headquartersreservation",
            name="environments",
            field=models.ManyToManyField(blank=True, related_name="reservations", to="hqbooking.headquartersenvironment"),
        ),
    ]
