# Generated by Codex on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hqbooking", "0004_environments_blocks"),
    ]

    operations = [
        migrations.CreateModel(
            name="LunchReservation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee_id", models.CharField(max_length=20)),
                ("reserved_date", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["reserved_date", "-created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(fields=("employee_id", "reserved_date"), name="uq_lunch_employee_date")
                ],
            },
        ),
    ]
