# Generated by Django 5.0.6 on 2026-06-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hqbooking', '0010_tire_run_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchreservation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
