# Generated by Django 5.0.6 on 2026-07-02 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hqbooking', '0011_alter_lunchreservation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucktirechange',
            name='tire_brand',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='trucktirechangehistory',
            name='action_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trucktirechangehistory',
            name='previous_tire_brand',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='trucktirechangehistory',
            name='tire_brand',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='trucktirechange',
            name='tire_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='trucktirechangehistory',
            name='previous_tire_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='trucktirechangehistory',
            name='tire_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=80)),
                ('serial_number', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('stock', 'Estoque'), ('installed', 'Instalado'), ('discarded', 'Descartado')], db_index=True, default='stock', max_length=20)),
                ('recap_count', models.PositiveSmallIntegerField(default=0)),
                ('current_tire_number', models.PositiveIntegerField(blank=True, null=True)),
                ('current_slot_label', models.CharField(blank=True, max_length=60, null=True)),
                ('registered_on', models.DateField(blank=True, null=True)),
                ('discarded_on', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=220, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tires', to='hqbooking.truck')),
            ],
            options={
                'ordering': ['serial_number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='trucktirechange',
            name='tire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truck_assignments', to='hqbooking.tire'),
        ),
        migrations.AddField(
            model_name='trucktirechangehistory',
            name='tire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truck_history_entries', to='hqbooking.tire'),
        ),
        migrations.CreateModel(
            name='TireMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('register', 'Cadastro'), ('install', 'Instalacao'), ('to_stock', 'Movido para estoque'), ('retread', 'Recape'), ('discard', 'Descarte')], default='register', max_length=20)),
                ('tire_number', models.PositiveIntegerField(blank=True, null=True)),
                ('position_label', models.CharField(blank=True, max_length=60, null=True)),
                ('movement_date', models.DateField(blank=True, null=True)),
                ('odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=220, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='hqbooking.tire')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tire_movements', to='hqbooking.truck')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
