# Generated by Django 5.0.6 on 2026-07-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hqbooking', '0012_trucktirechange_tire_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='status',
            field=models.CharField(choices=[('stock', 'Estoque'), ('installed', 'Instalado'), ('retreading', 'Em recapagem'), ('discarded', 'Descartado')], db_index=True, default='stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='tiremovement',
            name='movement_type',
            field=models.CharField(choices=[('register', 'Cadastro'), ('install', 'Instalacao'), ('to_stock', 'Movido para estoque'), ('to_retread', 'Enviado para recapagem'), ('from_retread', 'Retorno da recapagem'), ('retread', 'Recape'), ('discard', 'Descarte')], default='register', max_length=20),
        ),
    ]
