# Generated by Django 5.0.6 on 2026-07-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hqbooking', '0013_alter_tire_status_alter_tiremovement_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='last_retread_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tire',
            name='purchase_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tire',
            name='total_retread_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tiremovement',
            name='movement_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
