# Generated by Django 5.0.6 on 2026-07-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hqbooking', '0014_tire_last_retread_cost_tire_purchase_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiremovement',
            name='movement_type',
            field=models.CharField(choices=[('register', 'Cadastro'), ('install', 'Instalacao'), ('reposition', 'Reposicionamento'), ('to_stock', 'Movido para estoque'), ('to_retread', 'Enviado para recapagem'), ('from_retread', 'Retorno da recapagem'), ('retread', 'Recape'), ('discard', 'Descarte')], default='register', max_length=20),
        ),
    ]
