# Generated by Django 5.0.6 on 2026-07-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hqbooking', '0015_alter_tiremovement_movement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRomaneioEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=20)),
                ('branch_code', models.CharField(max_length=20)),
                ('sequence_record', models.CharField(max_length=40)),
                ('user_code', models.CharField(max_length=40)),
                ('generated_date', models.DateField()),
                ('generated_time', models.TimeField()),
                ('volume_quantity', models.PositiveIntegerField()),
                ('romaneio_weight', models.DecimalField(decimal_places=3, max_digits=14)),
                ('barcode_payload', models.TextField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pendente'), ('success', 'Enviado'), ('error', 'Erro')], default='pending', max_length=10)),
                ('sync_message', models.CharField(blank=True, max_length=255, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
