# Generated by Django 5.0.6 on 2026-09-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hqbooking', '0016_simulationromaneioentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationromaneioentry',
            name='client_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
