# Generated by Django 5.0.6 on 2026-09-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hqbooking', '0017_simulationromaneioentry_client_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='dot_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tire',
            name='groove_depth_mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tire',
            name='size_spec',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='tire',
            name='tire_model',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='tiremovement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tires/movements/%Y/%m/'),
        ),
    ]
