# Generated by Django 5.0.6 on 2026-09-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hqbooking', '0018_tire_dot_code_tire_groove_depth_mm_tire_size_spec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationromaneioentry',
            name='address_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='simulationromaneioentry',
            name='package_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='simulationromaneioentry',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('success', 'Enviado'), ('error', 'Erro'), ('duplicate', 'Já contabilizado')], default='pending', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='simulationromaneioentry',
            constraint=models.UniqueConstraint(condition=models.Q(('sync_status', 'success'), models.Q(('package_code', ''), _negated=True)), fields=('package_code',), name='uq_romaneio_package_success'),
        ),
    ]
