# Generated by Django 5.0.6 on 2026-09-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hqbooking', '0019_romaneio_package_address_duplicate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='simulationromaneioentry',
            name='uq_romaneio_package_success',
        ),
        migrations.AddField(
            model_name='simulationromaneioentry',
            name='record_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Separar'), (2, 'Guardar'), (3, 'Paletizar'), (4, 'Carregar')], db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='simulationromaneioentry',
            constraint=models.UniqueConstraint(condition=models.Q(('sync_status', 'success'), models.Q(('package_code', ''), _negated=True)), fields=('package_code', 'record_type'), name='uq_romaneio_package_stage_success'),
        ),
    ]
