# Generated by Django 5.0.6 on 2026-09-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hqbooking', '0020_remove_simulationromaneioentry_uq_romaneio_package_success_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationromaneioentry',
            name='romaneio_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
