# Generated by Django 5.0.6 on 2026-09-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hqbooking', '0021_simulationromaneioentry_romaneio_meters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationromaneioentry',
            name='record_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Separar'), (2, 'Guardar'), (3, 'Paletizar'), (4, 'Carregar'), (5, 'Contagem de Estoque')], db_index=True, null=True),
        ),
    ]
